#!/bin/env bash

SRC="${1}";

if test ! -f "${SRC}"; then
	echo "'${SRC}' doesn't exists";
	exit 1;
fi

SUITES=$(cat "${SRC}" | sed -nr 's/^SUITE *\( *([^ ]+) *\) *$/\1/p');

cat << EOF
#include "greatest.h"

$(printf "SUITE(%s);\n" ${SUITES})

GREATEST_MAIN_DEFS();
int main(int argc, char **argv) {
GREATEST_MAIN_BEGIN();
$(printf "RUN_SUITE(%s);\n" ${SUITES})
GREATEST_MAIN_END();
}
EOF
