#!/usr/bin/env bash

export RUNNER="${1}";
shift 1;

my::run_builtin()
{
	if [[ -n "${TBLTN_GDB}" ]]; then
		gdb											\
			--tui									\
			-ex "break run_bltn.c:run_builtin"		\
			-ex "run"								\
			-ex "step"								\
			--args "${RUNNER}" "${@}" </dev/tty >/dev/tty;
		exit 0;
	fi
	timeout							\
		--verbose					\
		--kill-after=5s				\
		3s							\
		valgrind					\
			--quiet					\
			--leak-check=full		\
			--show-reachable=yes	\
			-- "${RUNNER}" "${@}";
}

source shunit2
