#!/usr/bin/env bash

SRC="${1}";

if test ! -f "${SRC}"; then
	echo "'${SRC}' doesn't exists";
	exit 1;
fi

B="[[:blank:]]";
NB="[^[:blank:]]";
PATTERN="^SUITE${B}*\(${B}*(${NB}+)${B}*\)";

cat << EOF
#include "greatest.h"

$(sed -nr "s/${PATTERN}/SUITE(\1);/p" "${SRC}")

GREATEST_MAIN_DEFS();
int main(int argc, char **argv)
{
	GREATEST_MAIN_BEGIN();
	$(sed -nr "s/${PATTERN}/RUN_SUITE(\1);/p" "${SRC}")
	GREATEST_MAIN_END();
}
EOF
